import type { HCP } from "@/context/hcp-context";

// ./data.tsx
export const mockHCPs: HCP[] = [
  {
    id: "emily-carter",
    name: "Dr. Emily Carter",
    title: "Cardiologist at HCMC",
    image:
      "https://images.pexels.com/photos/15770179/pexels-photo-15770179.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=emily-carter&size=80",
    education: "Harvard Medical University - Cardiology Degree",
    specialization: "Specialization in Heart Health",
    peers: 1000,
    connectionRate: 95,
    isCenter: true,
    x: 0,
    y: 0,
    yearsOfExperience: 15,
    headline: "Leading Cardiologist with a Focus on Heart Health",
    bio: "Dr. Emily Carter is a renowned cardiologist with extensive experience in treating complex heart conditions.",
    patientServed: { noOfPatients: 2500, addition: 100 },
    successRate: { rate: 98, addition: 2 },
  },
  {
    id: "john-smith",
    name: "Dr. John Smith",
    title: "Neurologist at Mayo Clinic",
    image:
      "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=john-smith&size=80",
    education: "Johns Hopkins Medical School",
    specialization: "Neurosurgery",
    peers: 750,
    connectionRate: 88,
    isCenter: false,
    x: 150,
    y: -100,
    yearsOfExperience: 12,
    headline: "Expert in Neurological Disorders",
    bio: "Dr. John Smith specializes in advanced neurosurgical techniques and patient care.",
    patientServed: { noOfPatients: 1800, addition: 75 },
    successRate: { rate: 95, addition: 3 },
  },
  {
    id: "sarah-johnson",
    name: "Dr. Sarah Johnson",
    title: "Pediatrician at Children's Hospital",
    image:
      "https://images.pexels.com/photos/1128318/pexels-photo-1128318.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=sarah-johnson&size=80",
    education: "Stanford Medical School",
    specialization: "Child Healthcare",
    peers: 650,
    connectionRate: 92,
    isCenter: false,
    x: -120,
    y: 80,
    yearsOfExperience: 10,
    headline: "Dedicated Pediatrician for Child Wellness",
    bio: "Dr. Sarah Johnson is passionate about improving child health and development.",
    patientServed: { noOfPatients: 2000, addition: 80 },
    successRate: { rate: 96, addition: 2 },
  },
  {
    id: "michael-brown",
    name: "Dr. Michael Brown",
    title: "Orthopedic Surgeon",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=michael-brown&size=80",
    education: "Mayo Clinic Medical School",
    specialization: "Sports Medicine",
    peers: 580,
    connectionRate: 85,
    isCenter: false,
    x: 100,
    y: 120,
    yearsOfExperience: 8,
    headline: "Specialist in Sports Injury Recovery",
    bio: "Dr. Michael Brown excels in orthopedic surgery and sports medicine.",
    patientServed: { noOfPatients: 1500, addition: 60 },
    successRate: { rate: 93, addition: 4 },
  },
  {
    id: "lisa-davis",
    name: "Dr. Lisa Davis",
    title: "Dermatologist at UCLA Medical",
    image:
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=lisa-davis&size=80",
    education: "UCLA Medical School",
    specialization: "Skin Cancer Research",
    peers: 420,
    connectionRate: 90,
    isCenter: false,
    x: -150,
    y: -80,
    yearsOfExperience: 9,
    headline: "Innovator in Skin Cancer Treatment",
    bio: "Dr. Lisa Davis focuses on advanced dermatological treatments and research.",
    patientServed: { noOfPatients: 1200, addition: 50 },
    successRate: { rate: 94, addition: 3 },
  },
  {
    id: "robert-wilson",
    name: "Dr. Robert Wilson",
    title: "Oncologist at MD Anderson",
    image:
      "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=robert-wilson&size=80",
    education: "MD Anderson Cancer Center",
    specialization: "Cancer Treatment",
    peers: 890,
    connectionRate: 87,
    isCenter: false,
    x: 80,
    y: -150,
    yearsOfExperience: 14,
    headline: "Leader in Oncology and Cancer Care",
    bio: "Dr. Robert Wilson is dedicated to advancing cancer treatment methodologies.",
    patientServed: { noOfPatients: 2200, addition: 90 },
    successRate: { rate: 97, addition: 1 },
  },
  {
    id: "jennifer-lee",
    name: "Dr. Jennifer Lee",
    title: "Psychiatrist at Johns Hopkins",
    image:
      "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=jennifer-lee&size=80",
    education: "Johns Hopkins Medical School",
    specialization: "Mental Health",
    peers: 340,
    connectionRate: 91,
    isCenter: false,
    x: -100,
    y: 150,
    yearsOfExperience: 7,
    headline: "Advocate for Mental Health Awareness",
    bio: "Dr. Jennifer Lee provides compassionate care for mental health patients.",
    patientServed: { noOfPatients: 1000, addition: 40 },
    successRate: { rate: 92, addition: 3 },
  },
];

export const mockConnections = [
  {
    source: "emily-carter",
    target: "john-smith",
    type: "Co-authored 3 publications",
    strength: 3,
  },
  {
    source: "emily-carter",
    target: "sarah-johnson",
    type: "Shared workplace",
    strength: 2,
  },
  {
    source: "emily-carter",
    target: "michael-brown",
    type: "Conference collaboration",
    strength: 1,
  },
  {
    source: "emily-carter",
    target: "lisa-davis",
    type: "Research partnership",
    strength: 2,
  },
  {
    source: "john-smith",
    target: "sarah-johnson",
    type: "Medical board",
    strength: 1,
  },
  {
    source: "michael-brown",
    target: "lisa-davis",
    type: "Joint practice",
    strength: 2,
  },
];