import type { HCP } from "@/context/hcp-context";

// ./data.tsx
// ./data.tsx
export const mockHCPs: HCP[] = [
  // Original 7 entries
  {
    id: "emily-carter",
    name: "Dr. Emily Carter",
    title: "Cardiologist at HCMC",
    image:
      "https://images.pexels.com/photos/15770179/pexels-photo-15770179.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=emily-carter&size=80",
    education: "Harvard Medical University - Cardiology Degree",
    specialization: "Specialization in Heart Health",
    peers: 1000,
    connectionRate: 95,
    isCenter: true,
    x: 0,
    y: 0,
    yearsOfExperience: 15,
    headline: "Leading Cardiologist with a Focus on Heart Health",
    bio: "Dr. Emily Carter is a renowned cardiologist with extensive experience in treating complex heart conditions.",
    patientServed: { noOfPatients: 2500, addition: 100 },
    successRate: { rate: 98, addition: 2 },
  },
  {
    id: "john-smith",
    name: "Dr. John Smith",
    title: "Neurologist at Mayo Clinic",
    image:
      "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=john-smith&size=80",
    education: "Johns Hopkins Medical School",
    specialization: "Neurosurgery",
    peers: 750,
    connectionRate: 88,
    isCenter: false,
    x: 150,
    y: -100,
    yearsOfExperience: 12,
    headline: "Expert in Neurological Disorders",
    bio: "Dr. John Smith specializes in advanced neurosurgical techniques and patient care.",
    patientServed: { noOfPatients: 1800, addition: 75 },
    successRate: { rate: 95, addition: 3 },
  },
  {
    id: "sarah-johnson",
    name: "Dr. Sarah Johnson",
    title: "Pediatrician at Children's Hospital",
    image:
      "https://images.pexels.com/photos/1128318/pexels-photo-1128318.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=sarah-johnson&size=80",
    education: "Stanford Medical School",
    specialization: "Child Healthcare",
    peers: 650,
    connectionRate: 92,
    isCenter: false,
    x: -120,
    y: 80,
    yearsOfExperience: 10,
    headline: "Dedicated Pediatrician for Child Wellness",
    bio: "Dr. Sarah Johnson is passionate about improving child health and development.",
    patientServed: { noOfPatients: 2000, addition: 80 },
    successRate: { rate: 96, addition: 2 },
  },
  {
    id: "michael-brown",
    name: "Dr. Michael Brown",
    title: "Orthopedic Surgeon",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=michael-brown&size=80",
    education: "Mayo Clinic Medical School",
    specialization: "Sports Medicine",
    peers: 580,
    connectionRate: 85,
    isCenter: false,
    x: 100,
    y: 120,
    yearsOfExperience: 8,
    headline: "Specialist in Sports Injury Recovery",
    bio: "Dr. Michael Brown excels in orthopedic surgery and sports medicine.",
    patientServed: { noOfPatients: 1500, addition: 60 },
    successRate: { rate: 93, addition: 4 },
  },
  {
    id: "lisa-davis",
    name: "Dr. Lisa Davis",
    title: "Dermatologist at UCLA Medical",
    image:
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=lisa-davis&size=80",
    education: "UCLA Medical School",
    specialization: "Skin Cancer Research",
    peers: 420,
    connectionRate: 90,
    isCenter: false,
    x: -150,
    y: -80,
    yearsOfExperience: 9,
    headline: "Innovator in Skin Cancer Treatment",
    bio: "Dr. Lisa Davis focuses on advanced dermatological treatments and research.",
    patientServed: { noOfPatients: 1200, addition: 50 },
    successRate: { rate: 94, addition: 3 },
  },
  {
    id: "robert-wilson",
    name: "Dr. Robert Wilson",
    title: "Oncologist at MD Anderson",
    image:
      "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=robert-wilson&size=80",
    education: "MD Anderson Cancer Center",
    specialization: "Cancer Treatment",
    peers: 890,
    connectionRate: 87,
    isCenter: false,
    x: 80,
    y: -150,
    yearsOfExperience: 14,
    headline: "Leader in Oncology and Cancer Care",
    bio: "Dr. Robert Wilson is dedicated to advancing cancer treatment methodologies.",
    patientServed: { noOfPatients: 2200, addition: 90 },
    successRate: { rate: 97, addition: 1 },
  },
  {
    id: "jennifer-lee",
    name: "Dr. Jennifer Lee",
    title: "Psychiatrist at Johns Hopkins",
    image:
      "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=jennifer-lee&size=80",
    education: "Johns Hopkins Medical School",
    specialization: "Mental Health",
    peers: 340,
    connectionRate: 91,
    isCenter: false,
    x: -100,
    y: 150,
    yearsOfExperience: 7,
    headline: "Advocate for Mental Health Awareness",
    bio: "Dr. Jennifer Lee provides compassionate care for mental health patients.",
    patientServed: { noOfPatients: 1000, addition: 40 },
    successRate: { rate: 92, addition: 3 },
  },
  // First set of 7 new unique entries
  {
    id: "david-martin",
    name: "Dr. David Martin",
    title: "Gastroenterologist at Cleveland Clinic",
    image:
      "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=david-martin&size=80",
    education: "Yale Medical School",
    specialization: "Digestive Health",
    peers: 820,
    connectionRate: 89,
    isCenter: false,
    x: 200,
    y: 50,
    yearsOfExperience: 13,
    headline: "Expert in Gastrointestinal Disorders",
    bio: "Dr. David Martin is a leading specialist in diagnosing and treating digestive system issues.",
    patientServed: { noOfPatients: 1900, addition: 85 },
    successRate: { rate: 96, addition: 2 },
  },
  {
    id: "amy-thompson",
    name: "Dr. Amy Thompson",
    title: "Endocrinologist at Mass General",
    image:
      "https://images.pexels.com/photos/4152972/pexels-photo-4152972.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=amy-thompson&size=80",
    education: "Columbia Medical School",
    specialization: "Hormonal Disorders",
    peers: 510,
    connectionRate: 93,
    isCenter: false,
    x: -80,
    y: 200,
    yearsOfExperience: 11,
    headline: "Specialist in Endocrine Health",
    bio: "Dr. Amy Thompson focuses on managing diabetes and thyroid disorders with innovative treatments.",
    patientServed: { noOfPatients: 1600, addition: 70 },
    successRate: { rate: 94, addition: 3 },
  },
  {
    id: "thomas-clark",
    name: "Dr. Thomas Clark",
    title: "Pulmonologist at UCSF Medical",
    image:
      "https://images.pexels.com/photos/2380794/pexels-photo-2380794.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=thomas-clark&size=80",
    education: "UCSF Medical School",
    specialization: "Respiratory Medicine",
    peers: 670,
    connectionRate: 86,
    isCenter: false,
    x: 120,
    y: -200,
    yearsOfExperience: 10,
    headline: "Leader in Lung Health",
    bio: "Dr. Thomas Clark is dedicated to advancing treatments for chronic respiratory conditions.",
    patientServed: { noOfPatients: 1700, addition: 65 },
    successRate: { rate: 95, addition: 2 },
  },
  {
    id: "karen-white",
    name: "Dr. Karen White",
    title: "Rheumatologist at NYU Langone",
    image:
      "https://images.pexels.com/photos/3779707/pexels-photo-3779707.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=karen-white&size=80",
    education: "NYU Medical School",
    specialization: "Autoimmune Diseases",
    peers: 460,
    connectionRate: 90,
    isCenter: false,
    x: -200,
    y: -50,
    yearsOfExperience: 9,
    headline: "Innovator in Rheumatology",
    bio: "Dr. Karen White specializes in treating arthritis and other autoimmune conditions.",
    patientServed: { noOfPatients: 1300, addition: 55 },
    successRate: { rate: 93, addition: 3 },
  },
  {
    id: "james-king",
    name: "Dr. James King",
    title: "Urologist at Johns Hopkins",
    image:
      "https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=king-james&size=80",
    education: "Johns Hopkins Medical School",
    specialization: "Urological Surgery",
    peers: 700,
    connectionRate: 88,
    isCenter: false,
    x: 50,
    y: 250,
    yearsOfExperience: 14,
    headline: "Expert in Urologic Care",
    bio: "Dr. James King provides advanced surgical care for urological disorders.",
    patientServed: { noOfPatients: 2000, addition: 90 },
    successRate: { rate: 96, addition: 2 },
  },
  {
    id: "laura-green",
    name: "Dr. Laura Green",
    title: "Ophthalmologist at Wills Eye Hospital",
    image:
      "https://images.pexels.com/photos/3779707/pexels-photo-3779707.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=laura-green&size=80",
    education: "Penn Medicine",
    specialization: "Vision Care",
    peers: 390,
    connectionRate: 91,
    isCenter: false,
    x: -250,
    y: 100,
    yearsOfExperience: 8,
    headline: "Specialist in Eye Health",
    bio: "Dr. Laura Green is committed to preserving and enhancing patient vision.",
    patientServed: { noOfPatients: 1100, addition: 50 },
    successRate: { rate: 92, addition: 3 },
  },
  {
    id: "steven-hall",
    name: "Dr. Steven Hall",
    title: "Nephrologist at Cedars-Sinai",
    image:
      "https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=steven-hall&size=80",
    education: "Cedars-Sinai Medical School",
    specialization: "Kidney Health",
    peers: 550,
    connectionRate: 87,
    isCenter: false,
    x: 250,
    y: -100,
    yearsOfExperience: 12,
    headline: "Leader in Kidney Care",
    bio: "Dr. Steven Hall focuses on innovative treatments for kidney disease.",
    patientServed: { noOfPatients: 1400, addition: 60 },
    successRate: { rate: 94, addition: 2 },
  },
  // Second set of 7 unique entries
  {
    id: "anna-rodriguez",
    name: "Dr. Anna Rodriguez",
    title: "Cardiologist at Mount Sinai",
    image:
      "https://images.pexels.com/photos/4152972/pexels-photo-4152972.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=anna-rodriguez&size=80",
    education: "Icahn School of Medicine",
    specialization: "Heart Rhythm Disorders",
    peers: 950,
    connectionRate: 94,
    isCenter: false,
    x: 0,
    y: 300,
    yearsOfExperience: 16,
    headline: "Pioneer in Arrhythmia Treatment",
    bio: "Dr. Anna Rodriguez is renowned for her expertise in heart rhythm management.",
    patientServed: { noOfPatients: 2800, addition: 110 },
    successRate: { rate: 97, addition: 2 },
  },
  {
    id: "mark-taylor",
    name: "Dr. Mark Taylor",
    title: "Neurologist at Stanford Health",
    image:
      "https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=mark-taylor&size=80",
    education: "Stanford Medical School",
    specialization: "Stroke Care",
    peers: 720,
    connectionRate: 89,
    isCenter: false,
    x: 300,
    y: -50,
    yearsOfExperience: 11,
    headline: "Specialist in Stroke Prevention",
    bio: "Dr. Mark Taylor is dedicated to improving outcomes after stroke patients.",
    patientServed: { noOfPatients: 1750, addition: 70 },
    successRate: { rate: 95, addition: 3 },
  },
  {
    id: "elizabeth-adams",
    name: "Dr. Elizabeth Adams",
    title: "Pediatric Surgeon at Boston Children’s",
    image:
      "https://images.pexels.com/photos/3778743/pexels-photo-3778743.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=elizabeth-adams&size=80",
    education: "Harvard Medical School",
    specialization: "Pediatric Oncology",
    peers: 680,
    connectionRate: 91,
    isCenter: false,
    x: -300,
    y: 150,
    yearsOfExperience: 13,
    headline: "Expert in Pediatric Surgery",
    bio: "Dr. Elizabeth Adams specializes in complex surgical procedures for children with cancer.",
    patientServed: { noOfPatients: 1900, addition: 80 },
    successRate: { rate: 96, addition: 2 },
  },
  {
    id: "william-scott",
    name: "Dr. William Scott",
    title: "Orthopedic Surgeon at HSS",
    image:
      "https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=william-scott&size=80",
    education: "Weill Cornell Medical College",
    specialization: "Joint Reconstruction",
    peers: 600,
    connectionRate: 88,
    isCenter: false,
    x: 50,
    y: -300,
    yearsOfExperience: 10,
    headline: "Leader in Joint Replacement",
    bio: "Dr. William Scott excels in performing advanced joint reconstruction surgeries.",
    patientServed: { noOfPatients: 1600, addition: 65 },
    successRate: { rate: 94, addition: 3 },
  },
  {
    id: "susan-morgan",
    name: "Dr. Susan Morgan",
    title: "Dermatologist at Kaiser Permanente",
    image:
      "https://images.pexels.com/photos/4152972/pexels-photo-4152972.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=susan-morgan&size=80",
    education: "UC San Diego Medical School",
    specialization: "Mohs Surgery",
    peers: 470,
    connectionRate: 90,
    isCenter: false,
    x: -50,
    y: 300,
    yearsOfExperience: 9,
    headline: "Specialist in Skin Surgery",
    bio: "Dr. Susan Morgan is an expert in Mohs surgery for skin cancer treatment.",
    patientServed: { noOfPatients: 1350, addition: 60 },
    successRate: { rate: 93, addition: 3 },
  },
  {
    id: "peter-nguyen",
    name: "Dr. Peter Nguyen",
    title: "Oncologist at Sloan Kettering",
    image:
      "https://images.pexels.com/photos/5327586/pexels-photo-5327586.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=peter-nguyen&size=80",
    education: "Weill Cornell Medical School",
    specialization: "Immunotherapy",
    peers: 910,
    connectionRate: 87,
    isCenter: false,
    x: 350,
    y: 0,
    yearsOfExperience: 15,
    headline: "Innovator in Cancer Immunotherapy",
    bio: "Dr. Peter Nguyen advances cancer care with cutting-edge immunotherapy treatments.",
    patientServed: { noOfPatients: 2400, addition: 95 },
    successRate: { rate: 97, addition: 1 },
  },
  {
    id: "rachel-young",
    name: "Dr. Rachel Young",
    title: "Psychiatrist at UCLA Neuropsychiatric",
    image:
      "https://images.pexels.com/photos/3778743/pexels-photo-3778743.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop",
    fallbackImage:
      "https://api.dicebear.com/9.x/identicon/svg?seed=rachel-young&size=80",
    education: "UCLA Medical School",
    specialization: "Anxiety Disorders",
    peers: 360,
    connectionRate: 92,
    isCenter: false,
    x: -350,
    y: -150,
    yearsOfExperience: 8,
    headline: "Advocate for Anxiety Management",
    bio: "Dr. Rachel Young provides empathetic care for patients with anxiety disorders.",
    patientServed: { noOfPatients: 1050, addition: 45 },
    successRate: { rate: 92, addition: 3 },
  },
];
export const mockConnections = [
  {
    source: "emily-carter",
    target: "john-smith",
    type: "Co-authored 3 publications",
    strength: 3,
  },
  {
    source: "emily-carter",
    target: "sarah-johnson",
    type: "Shared workplace",
    strength: 2,
  },
  {
    source: "emily-carter",
    target: "michael-brown",
    type: "Conference collaboration",
    strength: 1,
  },
  {
    source: "emily-carter",
    target: "lisa-davis",
    type: "Research partnership",
    strength: 2,
  },
  {
    source: "john-smith",
    target: "sarah-johnson",
    type: "Medical board",
    strength: 1,
  },
  {
    source: "michael-brown",
    target: "lisa-davis",
    type: "Joint practice",
    strength: 2,
  },
];